config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match '/signin', to: 'users#signin', as: 'signin', via: [:post, :get]
  get '/login', to: 'login#new', as: 'login'
  post '/login', to: 'login#create', as: 'login_create'
  delete '/logout', to: 'login#logout', as: 'logout'
  #resources :users

  get '/dashboard', to: 'application#dashboard', as: 'dashboard'


  get '/operadores', to: 'operadores#index', as: 'operadores'
  match '/operadores/create', to: 'operadores#create', as: 'operadores_create', via: [:post, :get]
  match '/operadores/update/:id', to: 'operadores#update', as: 'operadores_update', via: [:patch, :get]

  get '/docs', to: 'docs#index', as: 'docs'
  get '/docs/create', to: 'docs#create', as: 'docs_create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/operador.rb
class Operador < ApplicationRecord
    self.table_name = "operadores"
    has_many :atendimentos, class_name: "OperadorAtendimento",
                            foreign_key: "operador_id"
    accepts_nested_attributes_for :atendimentos, allow_destroy: true
end

app/models/operador_atendimento.rb
class OperadorAtendimento < ApplicationRecord
    self.table_name = "operadores_atendimentos"
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :phone

    PHONE_REGEXP = /\A\([0-9]{2}\) [0-9]{4,5}-[0-9]{4}\Z/

    validates :name, presence: true
    validates :email, 
        format: { with: URI::MailTo::EMAIL_REGEXP },
        uniqueness: { case_sensitive: false }
    validates :phone, 
        format: { with: User::PHONE_REGEXP },
        allow_blank: true
    validates :password, length: { minimum: 6 }

    has_secure_password

    def before_save(record)
        record.email = record.email.downcase
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :ui
    include UsersHelper

    def dashboard
        @ui.page_title = 'Dashboard'
        render 'admin/dashboard'
    end

    protected
    def add_message(type, message)
        flash[type] = message
    end

    def add_message_now(type, message)
        flash.now[type] = message
    end

    private
    def ui
        @ui = Admin::Ui.new

        @ui.project_name = 'App'

        @ui.add_menu('dashboard', 'Dashboard', dashboard_path)
        @ui.add_menu('teste', 'Teste')
        @ui.add_menu('operadores', 'Operadores', operadores_path)

        puts @ui.menu
    end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController

    def index
       path = Rails.root.join("public", "docs", "*")
       @docs = Dir.glob(path)
    end

    def create
        DocJob.perform_later        
        redirect_to docs_path
    end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    def new
    end

    def create
        email = params[:login][:email]
        password = params[:login][:password]

        user = User.find_by(email: email)

        if user && user.authenticate(password)
            # ok
            auth user.id

            # user logged url
            redirect_to login_path
        else
            # error
            add_message(:danger, "Erro de login")
            redirect_to login_path
        end
    end

    def logout
        user_logout
        redirect_to login_path
    end
end

app/controllers/operadores_controller.rb
class OperadoresController < ApplicationController

    def index
        #OperadorMailer.welcome.deliver_later

        foo = Luan::Foo.new
        puts foo.hello

        @per_page = 10
        @page = 1

        if request.query_parameters.has_key? :page
            request_page = request.query_parameters[:page].to_i
            if request_page > 1
                @page = request_page
            end 
        end

        @data_total = query.count(:id).length
        @data_pages = @data_total/@per_page
        @data = query
            .limit(@per_page)
            .offset((@page-1)*@per_page)
    end

    def create
        @operador = Operador.new

        if request.post?
            @operador.attributes = params.require(:operador).permit(:nome, :email, :atendimentos_attributes => [:tempo])
            @operador.save
            add_message(:success, 'Registro criado com sucesso')
            redirect_to operadores_update_path(@operador.id)
        end
    end

    def update
        @operador = Operador.find(params[:id])

        if request.patch?
            @operador.attributes = params.require(:operador).permit(:nome, :email, :atendimentos_attributes => [:id, :tempo, :_destroy])
            @operador.save
            add_message_now(:success, 'Registro atualizado com sucesso')
        end
    end

    protected
    def query
        @termo = nil

        if request.query_parameters.has_key? :buscar
            if request.query_parameters[:buscar].has_key? :termo
                @termo = request.query_parameters[:buscar][:termo]
            end
        end

        q = Operador
            .select('operadores.*')
            .where("email LIKE :termo OR nome LIKE :termo", {
                termo: "%#{@termo}%"
            })
            .left_outer_joins(:atendimentos)
            .includes(:atendimentos)
            .group(:id)
        q
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def signin
        @user = User.new

        if request.post?
            user_params = params.require(:user).permit(:name, :email, :password, :password_confirmation)
            @user.attributes = user_params
            if @user.save
                # Handle a successful save.
            end

            if !@user.errors.empty?
                add_message(:danger, "Corrija os erros do formulário para continuar")
            end

        end
    end

    def create
        
        
    end

end

app/helpers/admin.rb
module Admin

    class Ui
        attr_accessor :project_name, :page_title
        attr_reader :menu
        
        def add_menu(name, title, uri=nil)
            if @menu.nil?
                @menu = []
            end

            @menu.push({
                name: name,
                title: title,
                uri: uri
            })
        end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper

    def class_string(*items)
        output = []

        items.each do |item|
            if (item.is_a?(Hash))
                item.each do |item_class, item_if|
                    if item_if
                        output.push(item_class)
                    end
                end
            else
                output.push(item)
            end            
        end

        output.join(" ")
    end
    
end

app/helpers/users_helper.rb
module UsersHelper

    def auth(user_id)
        session[:user_id] = user_id
    end

    def current_user
        if session[:user_id]
            user = User.find(session[:user_id])

            if user
                @user = user
            end
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def user_logout
        session.delete(:user_id)
    end

end

app/views/admin/dashboard.html.erb
<h2>Dashboard</h2>

app/views/application/_atendimento_fields.html.erb
<div class="nested-fields">
    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <%= f.label "Tempo" %>
                <%= f.text_field :tempo, class: 'form-control' %>
            </div>
        </div>

        <%= link_to_remove_association icon('far', 'trash-alt'), f, class: 'btn btn-danger' %>
    </div>

    <hr class="m-0">
</div>

app/views/docs/index.html.erb
<% if !@docs.blank? %>
<ol>
    <% @docs.each do |doc| %>
    <li>
        <a href="<%= "/docs/" + File.basename(doc) %>" target="_blank">
            <%= File.basename(doc) %>
        </a>
    </li>
    <% end %>
</ol>
<% end %>

<hr>

<a href="<%= docs_create_path %>" class="btn btn-primary">Novo</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <style>
      .invalid-feedback {
        display: block;
      }
    </style>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#"><%= @ui.project_name %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <% if !@ui.menu.nil? %>
          <ul class="navbar-nav mr-auto">
            <% @ui.menu.each do |menu| %>
            <li class="nav-item">
              <a class="nav-link" href="<%= menu[:uri] %>"><%= menu[:title] %></a>
            </li>
            <% end %>
          </ul>
          <% end %>
        </div>
      </nav>

      <div class="py-4">

      <% if !flash.blank? %>
        <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %> alert-dismissible fade show">
            <%= message %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <% end %>
      <% end %>

      <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/login/new.html.erb
<% if logged_in? %>
<h1><%= debug current_user.inspect %></h1>
<h1>Logged In: <%= debug logged_in? %></h1>
<%= link_to  "Sair", logout_path, method: :delete %>
<% end %>

<div class="row justify-content-md-center">
    <div class="col col-lg-6">

    <%= @name %>

<div class="card">
    <div class="card-header">Sing Up</div>
    <div class="card-body">

    <%= form_for(:login, url: login_path) do |f| %>
        <div class="form-group">
            <%= f.text_field(:email, class: "form-control") %>
        </div>

        <div class="form-group">
            <%= f.password_field(:password, class: "form-control") %>
        </div>
        
        <%= f.submit "Sign up now!", class: "btn btn-block btn-primary" %>
    <% end %>
    </div>
</div>

</div>
</div>

app/views/operadores/_form.html.erb
<%= form_for @operador, url: url do |f| %>
    <div class="form-group">
        <%= f.label "Nome" %>
        <%= f.text_field :nome, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label "E-mail" %>
        <%= f.text_field :email, class: 'form-control' %>
    </div>

    <div class="card mb-3">
        <div class="card-header">Atendimentos</div>
        <%= f.fields_for :atendimentos do |atendimento| %>
            <%= render 'atendimento_fields', :f => atendimento %>
        <% end %>
        <div class="card-footer text-right">
            <%= link_to_add_association icon('fas', 'plus'), f, :atendimentos, class: 'btn btn-success' %>
        </div>
    </div>

    <%= f.submit "Salvar Operador", class: "btn btn-primary" %>
<% end %>

app/views/operadores/create.html.erb
<p>Create</p>

<%= render 'operadores/form', url: operadores_create_path %>

app/views/operadores/index.html.erb
<h2>List Operadores</h2>

<%= form_tag(operadores_path, method: "get", class: 'form-inline') do |f| %>
    <div class="form-group">
        <%= text_field(:buscar, :termo, class: 'form-control', value: @termo) %>
    </div>

    <%= submit_tag('Buscar', class: 'btn btn-secondary') %>
<% end %>

<p><%= @data_total %> resultados encontrados</p>

<% if @data_total > 0 %>
<table class="table">

    <tr>
        <th>Nome</th>
        <th>E-mail</th>
        <th>Atendimentos</th>
        <th></th>
    </tr>

    <% @data.each do |item| %>
    <tr>
        <td><%= item.nome %></td>
        <td><%= item.email %></td>
        <td><%= item.atendimentos.length %></td>
        <td width="1">
            <a href="<%= operadores_update_path(item.id) %>" class="btn btn-primary">
                <%= icon('far', 'edit') %>
            </a>
        </td>
    </tr>
    <% end %>

</table>
<% end %>

<h1><%= @page %></h1>

<% if @data_pages > 1 %>
<ul class="pagination">
    <% 1.step(@data_pages, 1) do |p| %>
    <li class="<%= p==@page ? 'page-item active' : 'page-item' %>">
        <a class="page-link" href="<%= operadores_path %>?page=<%= p %>"><%= p %></a>
    </li>
    <% end %>
</ul>
<% end %>

app/views/operadores/update.html.erb
<p>Update</p>

<%= render 'operadores/form', url: operadores_update_path %>

app/views/users/signin.html.erb
<h2>Sign In</h2>

<h1><%= debug @user.errors[:name].empty?.inspect %></h1>

<%= form_for @user, url: signin_path, html: {class: "nifty_form"} do |f| %>
	<div class="form-group">
		<%= label_tag(:user_name, "Nome:") %>
		<%= f.text_field :name, 
			class: class_string("form-control", "is-invalid": !@user.errors[:name].empty?) %>
		<% if !@user.errors[:name].empty? %>
		<div class="invalid-feedback"><%= @user.errors[:name].first %></div>
		<% end %>
	</div>

	<div class="form-group">
		<%= label_tag(:user_email, "E-mail:") %>
		<%= f.text_field :email, 
			class: class_string("form-control", "is-invalid": !@user.errors[:email].empty?) %>
		<% if !@user.errors[:email].empty? %>
		<div class="invalid-feedback"><%= @user.errors[:email].first %></div>
		<% end %>
	</div>

	<div class="form-group">
		<%= label_tag(:user_password, "Senha:") %>
		<%= f.password_field :password, 
			class: class_string("form-control", "is-invalid": !@user.errors[:password].empty?) %>
		<% if !@user.errors[:password].empty? %>
		<div class="invalid-feedback"><%= @user.errors[:password].first %></div>
		<% end %>
	</div>

	<div class="form-group">
		<%= label_tag(:user_password_confirmation, "Confirmar Senha:") %>
		<%= f.password_field :password_confirmation, 
			class: class_string("form-control", "is-invalid": !@user.errors[:password_confirmation].empty?) %>
		<% if !@user.errors[:password_confirmation].empty? %>
		<div class="invalid-feedback"><%= @user.errors[:password_confirmation].first %></div>
		<% end %>
	</div>

	<%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>

<pre><%= debug @user.inspect %></pre>